favicon: null
name: sawalker999 - Rodan+Fields
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.173151055816561
  brandStrength: 0.820957261370495
  rhythmicContrast: 0.002328473376110196
  brandColors:
    - '#292c31'
    - '#728491'
    - '#bcbbc1'
    - '#010101'
    - '#fdf6c0'
  lightness: 0.9503041924908757
typography_spectrum: 0.5854502881411463
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9436089
analytics:
  twitter: null
  google: null
  facebook: null
